[package]
name = "qcore-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "qcore_rs"
path = "src/lib.rs"

[[bin]]
name = "qcore-rs"
path = "src/main.rs"

[dependencies]
qlib-rs = { "path"="../qlib-rs" }
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.1"
tokio-stream = "0.1.17"
tokio-tungstenite = "0.21"
uuid = { version = "1.0", features = ["v4"] }
