[package]
name = "qcore-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
clap = "4.5.40"
openraft = "0.9.20"
qlib-rs = { "path"="../qlib-rs" }
reqwest = "0.12.20"
serde = "1.0.219"
serde_json = "1.0.140"
tokio = "1.45.1"
